### ISSUE TITLE
一点优化建议

### ISSUE THREAD

**Issue by a495433** [260721735/ginRouteAutoRegister#1]
AutoRoute.go 文件中  
AutoHand 中
//这里未判定 controllerValue.Method(i) 的接收参数 只有一个 且为 *gin.Context 使用时要注意
methods.maps[method][pkgName][strings.ToLower(strings.Replace(subLocation, method, "", 1))] = controllerValue.Method(i)

**Comment by 260721735** [comment]
感谢使用，已在https://github.com/260721735/ginRouteAutoRegister/commit/ac4f59512c4838c0276338a7f7ad05760d8a11de 修复
